### ISSUE TITLE
Analyst/Editor/Engineer views

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#20]
I'd really like to see these views merged into one view.  The workflow for these parts of the IG never really materialized the way we thought it would and now having to switch between the 3 is a frustrating.

Also, when we copy templates (which is TONS) it is impossible to see if there are descriptions/labels that you might want to edit or delete without actually changing the view and looking to see if there is something there. This makes it super easy to miss stuff and leave text that shouldn't be in your new template. Same goes for custom Schematron.

TRIF-1165 and TRIF-1192

**Comment by seanmcilvenna** [comment]
This is a good idea, Sarah. I have considered re-designing the template editor using angular.js so that it performs better, and is a little cleaner in code. Perhaps in the near future I will start this effort, and incorporate this idea at the same time. I considered creating right-sided tabs for the properties of constraints, grouping them a little different. Perhaps I will draw a mockup and see what you think.

**Comment by meenaxigosai** [comment]
Hello @minigrrl ,

I have created TRIF-1356 to track this request, and therefore will close out this GITHUB ticket.  We are moving to using JIRA Support Desk instead of GITHUB.

Best Regards,

Meenaxi Gosai
