### ISSUE TITLE
System.Web.Mvc in Trifolia.Authorization

### ISSUE THREAD

**Issue by qagwaai** [lantanagroup/trifolia#21]
In a clean pull, with a new OS, System.Web.Mvc in Trifolia.Authorization is an unsatisfied reference.  Following this procedure [this note from stack overflow](http://stackoverflow.com/questions/14824228/cs0234-mvc-does-not-exist-in-the-system-web-namespace), and removing/readding the reference seems to do fix the reference.  Only need to install AspNetMVC3ToolsUpdateSetup.exe.

**Comment by seanmcilvenna** [comment]
Hi qagwaii, I will check this out sometime next week. Glad to hear you're interested in looking at the code. Out of curiosity, are you intending to develop customizations for it, enhance existing functionality, or just play with it?

**Comment by seanmcilvenna** [comment]
@qagwaai, I took a bit of a look at this... The reference is pointing to "..\packages\Microsoft.AspNet.Mvc.4.0.20710.0\lib\net40\System.Web.Mvc.dll". This is a Nuget package that should be installed by VS/nuget when you build the projects (and VS tells Nuget to do a restore). You could also force the nuget package restore by install [nuget.exe](https://dist.nuget.org/index.html) and running the [restore](https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#restore) command. This SHOULD install the package that has this dll in the correct location for System.Authorization to resolve the reference.

**Comment by qagwaai** [comment]
@seanmcilvenna - we are not sure at the moment, but I think the initial thought is to implement internally to start.  Have you discussed any installations on Azure?  Specifically, we were thinking of leveraging Azure AD.

**Comment by seanmcilvenna** [comment]
Trifolia supports OAuth2.0, as does Azure AD. So, it should work fine to use Azure AD for authentication in Trifolia. You will need to, of course, modify the configuration so that it points to the correct azure ad endpoints, with the correct app id and secret key, but otherwise it should work fine. I actually initially implemented OAuth2.0 using Azure, but found that there were limited options for self-service using Azure AD, so we ended up going with auth0.com because of the extended support for self-service. But, if you do not need your users to be able to register themselves or maintain their own authentication accounts, then Azure AD should work fine.

**Comment by seanmcilvenna** [comment]
Have not heard back from you in over two weeks regarding this issue. I'm going to close it out. If this is still an issue and you need further clarification or changes, we can re-open the issue.
