### ISSUE TITLE
Export to MS Word Save as default doesn't work

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#26]
Export to MS Word Save as default doesn't work

I'm desperate to have this work.  

Right now it doesn't save when you change the first drop down alpha-hierarchical.

It also doesn't save templates you uncheck on the templates tab.  It's SUPER time consuming and error prone to have to keep setting these every time you export (or every few times - these screens don't refresh if you add a new template and will export fewer templates than you actually have in the IG if you don't either refresh (causing you to lose changes) or re select export to word).

TRIF-1145

**Comment by seanmcilvenna** [comment]
@meenaxigosai , can you investigate a bit and report your findings? Please create a JIRA development ticket linking to this github issue, as well. Thanks

**Comment by meenaxigosai** [comment]
This issue has been tested in the Trifolia development environment and has been resolved in the development build.   The fix will be deployed to Trifolia production with the next release.

**Comment by meenaxigosai** [comment]
Hello Sarah,

The fix for this issue was tested and released to Trifolia Production on April 26th, 2017.

I will close this ticket at this time, but if you continue to encounter any problems with the default settings when exporting Word documents, please let us know and we will re-open and investigate.

Best Regards,

Meenaxi Gosai
QA Analyst/Engineer
Lantana Consulting Group
t: 360.450.0545
Maple Ridge—BC PST

www.lantanagroup.com
Blog | Twitter | LinkedIn
