### ISSUE TITLE
Jeff Brown at ASCO unable to access Account

### ISSUE THREAD

**Issue by ZGLantana** [lantanagroup/trifolia#28]
Entering this on behalf of Jeff Brown.
Jeff brown changed his email from  jeff.brown@asco.org but it is jeff.brown@cancerlinq.org and he can no longer access his account.

He needs to access the Clinical Oncology Treatment Plan and Summary IG.  

Please contact him directly.  Thank you.

**Comment by rgeimer** [comment]
Sean, please expedite.

**Comment by meenaxigosai** [comment]
Hello Jeff,

I have checked your account in Auth0 and I see an account exists with the updated e-mail address and that e-mail address has been verified.

Typically, once the Auth0 e-mail address is verified, when the user logs into Trifolia, the New Profile page will appear, where the user can enter name, phone, organization, etc.   Once the user complete the New Profile page, then a new Trifolia user account is created associated with the new e-mail address.

Can you please tell me what happens when you try to log into Trifolia Workbench?

Thank you,

Meenaxi

**Comment by rgeimer** [comment]
Emailed Jeff brown directly, since Zabrina opened this ticket on his behalf. Waiting on his confirmation that this is fixed. So far no response.

**Comment by rgeimer** [comment]
Jeff confirmed via email that his access is restored.
