### ISSUE TITLE
Invalid message "Constraints on the template are out of order..."

### ISSUE THREAD

**Issue by minigrrl** [lantanagroup/trifolia#5]
No reason for getting this error – all I’ve done is copied a c-cda template, so there should be no constraints out of order and there has been no update to the Schema (it's from the latest c-cda). I've experienced this a few times since the latest release.
![2016-10-19_17-45-49](https://cloud.githubusercontent.com/assets/14354654/19510255/b8855082-9625-11e6-8fd1-614dcce390df.jpg)

**Comment by wendywise** [comment]
TRIF-1117

**Comment by meenaxigosai** [comment]
It has been determined that this issue is no longer appearing in the current build.  Please see notes below.

Arvind Jagannathan added a comment - 04/Apr/17 10:57 AM

When I talked with Sarah about ways to reproduce this issue, she couldn't think of how it was that she managed to have the problem occur for her. The only thing that made sense to us at the time was that we thought it was some kind of remnant of versioning or copying that wasn't caught during creation. She and I both agreed that this is probably something that we can ignore for the time being but if it comes back and is an problem again in the future, and we can actually manage to find where it's happening, we can dig back into it. 
Thanks!
