### ISSUE TITLE
Generated samples of <value> not including xsi:type attribute

### ISSUE THREAD

**Issue by russellott** [lantanagroup/trifolia#51]
The autogenerated samples of <value> attributes where xsi:type has been constrained do not include the xsi:type.

Example:

8. SHALL contain exactly one [1..1] value with @xsi:type="CD" (CONF:4376-856) such that it

Generated sample:
<value code="XXX" />

Should generate as follows:
<value xsi:type="CD" code="XXX" />

To be clear - this isn't urgent and needed for balloting or anything, but something you probably want to eventually fix.

**Comment by meenaxigosai** [comment]
Hello Russell,

Thank you for reporting this issue.   I'm afraid I cannot see the *Generated Sample* or the *Should generate as follows* in the GITHUB description of the issue.   

Could you please re-attach the screen shot or text examples of the problem to the ticket, so that I can investigate and discuss with our engineering team.

Thank you,


Meenaxi Gosai
Technical Analyst 
t: 360-450-0545
Maple Ridge, BC (Pacific Time)

**Comment by meenaxigosai** [comment]
Hello Russell,

Thank you for reporting this issue.  We have investigated and have been able to identify the problem you have discovered.  JIRA ticket TRIF-1335 has been created to address this issue.

We will keep you updated on when the fix for this will be released to production.

Best Regards,

Meenaxi Gosai
Technical Analyst 
t: 360-450-0545
Maple Ridge, BC (Pacific Time)

**Comment by meenaxigosai** [comment]
Hello Russell,

The fix for this issue was deployed to production on November 7th, 2018, and as such I will close this ticket at this time.    If you experience any other issues, please feel free to reach out to our team via the JIRA  SupportDesk.

Best Regards,

Meenaxi Gosai
Technical Analyst
Lantana Consulting Group
t: 360-450-0545
Maple Ridge, BC (Pacific Time)
